[project]
authors = [
{name = "Geoff Hutchison", email = "geoff.hutchison@gmail.com"},
{name = "Logan Ward", email = "lward@anl.gov" },
]
name = "bouquet"
requires-python = ">= 3.11"
version = "0.5.0"
description = 'Molecular conformer optimization via Bayesian optimization'
readme = "README.md"
dependencies = [
    "rdkit",
    "networkx",
    "torch",
    "gpytorch",
    "botorch",
    "ase",
    "torchani",  # optional: move here if you don't need GPU
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
openbabel = "*"
xtb-python = "*"
psi4 = "*"

