[project]
authors = [
{name = "Geoff Hutchison", email = "geoff.hutchison@gmail.com"}
{name = "Logan Ward", email = "lward@anl.gov" }
]
name = "bouquet"
requires-python = ">= 3.11"
version = "0.5.0"
description = 'Conformer optimization via Bayesian optimization'

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "linx-aarch64", "osx-64", "osx-arm64"]

[tool.pixi.tasks]

[tool.pixi.dependencies]
openbabel = "*"
networkx = "*"
pytorch = "*"
gpytorch = "*"
botorch = "*"
ase = "*"
torchani = "*"
xtb-python = "*"
psi4 = "*"
pip = "*"

